FROM node:18-alpine as build

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node . .
COPY --chown=node:node ./.env.production ./.env

RUN npm install 

RUN npm run build

CMD ["npm", "run", "start:prod"]

