FROM node:18-alpine as build

# Diretório de trabalho dentro do contêiner
WORKDIR /app

COPY package*.json ./
# Copie os arquivos do seu aplicativo para o diretório de trabalho
COPY . .

# Copie o .env production para o diretório de trabalho
COPY ./.env.production ./.env

RUN npm install -g @nestjs/cli

# Instale as dependências do Node.js
RUN npm install --quiet --no-optional --no-fund --loglevel=error

# Construa o aplicativo Node.js
RUN npm run build

EXPOSE 3333

CMD ["node", "dist/main.js"]

# CMD [ "npm", "run", "start:prod" ]
# CMD [ "./wait-for.sh", "db:3306", "--", "npm", "run", "start:prod" ]

# Exponha a porta do aplicativo Node.js

# Configuração do Nginx como um proxy reverso para o Node.js
# COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Comando para iniciar o aplicativo Node.js (ajuste conforme necessário)
# CMD ["npm", "start"]
